# PostgreSQL. Versions 9.1 and up are supported.

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: emp_mgmt_development
  username: mano
  password:
  host: localhost
  port: 5432

test:
  <<: *default
  database: emp_mgmt_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>