# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dd5dcfa36f01a2a9666ee4b7bb7d8a1430d9be18bd7409a27b6a09773a6c4141d91b8444b9d0766e913581dc501fa9840e03f7cf80c0da3566749fa2c05d22cb

test:
  secret_key_base: 384308e8da40ea647205c676750f0d7cd3383652ce2bc3e555a373fa7f7c274d51ee06008b16ba18065449d2ed175281a9911bf6fc08b5a60808731d80cc3d5d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
